// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type APIKey struct {
	Key         string `json:"key"`
	Description string `json:"description"`
	ExpiresAt   *int64 `json:"expiresAt,omitempty"`
	CreatedAt   int64  `json:"createdAt"`
}

type AddBatchDocumentInput struct {
	Key          string       `json:"key"`
	Lang         string       `json:"lang"`
	ContentMd    string       `json:"contentMd"`
	Meta         []*MetaInput `json:"meta,omitempty"`
	SaveRevision *bool        `json:"saveRevision,omitempty"`
}

type AddDocumentInput struct {
	Collection string       `json:"collection"`
	Key        string       `json:"key"`
	Lang       string       `json:"lang"`
	Meta       []*MetaInput `json:"meta,omitempty"`
	ContentMd  string       `json:"contentMd"`
	TTL        *int         `json:"ttl,omitempty"`
}

type AuthPayload struct {
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expiresAt"`
}

type BatchAddResult struct {
	Added   int      `json:"added"`
	Updated int      `json:"updated"`
	Failed  int      `json:"failed"`
	Errors  []string `json:"errors,omitempty"`
}

type CodeGraph struct {
	Collection string           `json:"collection"`
	Root       string           `json:"root"`
	Direction  string           `json:"direction"`
	Depth      int              `json:"depth"`
	Nodes      []*CodeGraphNode `json:"nodes"`
	Edges      []*CodeGraphEdge `json:"edges"`
	// True when a depth or degree limit cut the walk short.
	Truncated bool `json:"truncated"`
}

type CodeGraphEdge struct {
	From string `json:"from"`
	To   string `json:"to"`
	// uses-selector or imports
	Kind string `json:"kind"`
	// The symbol or path that justifies this edge.
	Symbol    string `json:"symbol"`
	Direction string `json:"direction"`
	// First occurrence of the symbol in the source document, 0 if not literal.
	FromLine *int `json:"fromLine,omitempty"`
	// First occurrence of the symbol in the target document, 0 if not literal.
	ToLine *int `json:"toLine,omitempty"`
}

type CodeGraphInput struct {
	Collection string `json:"collection"`
	Key        string `json:"key"`
	// in = what depends on this document, out = what it depends on, both (default)
	Direction *string `json:"direction,omitempty"`
	// Hops to follow, 1-3 (default: 1)
	Depth *int `json:"depth,omitempty"`
	// Maximum neighbours per node, 1-100 (default: 100)
	MaxDegree *int `json:"maxDegree,omitempty"`
	// Include the first line each edge's symbol appears on, both sides. Reads
	// document content, which a traversal otherwise never does.
	Lines *bool `json:"lines,omitempty"`
}

type CodeGraphNode struct {
	Key      string  `json:"key"`
	DocID    string  `json:"docId"`
	Lang     *string `json:"lang,omitempty"`
	Language *string `json:"language,omitempty"`
	Depth    int     `json:"depth"`
}

type CollectionStats struct {
	Name           string `json:"name"`
	DocumentCount  int    `json:"documentCount"`
	RevisionCount  int    `json:"revisionCount"`
	MetaIndexCount int    `json:"metaIndexCount"`
}

type CreateAPIKeyInput struct {
	Description string `json:"description"`
	ExpiresAt   *int64 `json:"expiresAt,omitempty"`
}

type CreateGroupInput struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Members     []string `json:"members"`
}

type Document struct {
	ID        string         `json:"id"`
	Key       string         `json:"key"`
	Lang      string         `json:"lang"`
	Meta      map[string]any `json:"meta"`
	ContentMd string         `json:"contentMd"`
	AddedAt   int64          `json:"addedAt"`
	UpdatedAt int64          `json:"updatedAt"`
	ExpiresAt *int64         `json:"expiresAt,omitempty"`
}

type DocumentConnection struct {
	Edges      []*DocumentEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type DocumentEdge struct {
	Cursor string    `json:"cursor"`
	Node   *Document `json:"node"`
}

type FTSInput struct {
	Collection string `json:"collection"`
	Query      string `json:"query"`
	Limit      *int   `json:"limit,omitempty"`
}

type FTSResponse struct {
	Results []*FTSResult `json:"results"`
	Total   int          `json:"total"`
}

type FTSResult struct {
	Document     *Document `json:"document"`
	Score        float64   `json:"score"`
	MatchedTerms []string  `json:"matchedTerms"`
}

type Group struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Members     []string `json:"members"`
	CreatedAt   int64    `json:"createdAt"`
}

type GroupPermission struct {
	GroupName  string `json:"groupName"`
	Collection string `json:"collection"`
	Read       bool   `json:"read"`
	Write      bool   `json:"write"`
	Admin      bool   `json:"admin"`
}

type IngestDocumentInput struct {
	URL                *string      `json:"url,omitempty"`
	Key                *string      `json:"key,omitempty"`
	Lang               string       `json:"lang"`
	ContentMd          string       `json:"contentMd"`
	Meta               []*MetaInput `json:"meta,omitempty"`
	ExtractFrontmatter *bool        `json:"extractFrontmatter,omitempty"`
	ScrapedAt          *int         `json:"scrapedAt,omitempty"`
	Scraper            *string      `json:"scraper,omitempty"`
	TTL                *int         `json:"ttl,omitempty"`
}

type IngestOptionsInput struct {
	SkipDuplicates          *bool `json:"skipDuplicates,omitempty"`
	SkipEmbeddings          *bool `json:"skipEmbeddings,omitempty"`
	SkipFts                 *bool `json:"skipFts,omitempty"`
	SkipWebhooks            *bool `json:"skipWebhooks,omitempty"`
	AutoConfigureCollection *bool `json:"autoConfigureCollection,omitempty"`
	SaveRevision            *bool `json:"saveRevision,omitempty"`
}

type IngestResult struct {
	Added      int      `json:"added"`
	Updated    int      `json:"updated"`
	Skipped    int      `json:"skipped"`
	Failed     int      `json:"failed"`
	Errors     []string `json:"errors,omitempty"`
	Collection string   `json:"collection"`
	DurationMs int      `json:"durationMs"`
}

type MetaInput struct {
	Key    string   `json:"key"`
	Values []string `json:"values"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RegisterWebhookInput struct {
	URL        string   `json:"url"`
	Events     []string `json:"events"`
	Collection string   `json:"collection"`
}

type Schema struct {
	Collection string `json:"collection"`
	Schema     string `json:"schema"`
	Enabled    bool   `json:"enabled"`
}

type SearchInput struct {
	Collection string       `json:"collection"`
	FilterMeta []*MetaInput `json:"filterMeta,omitempty"`
	Sort       *string      `json:"sort,omitempty"`
	Asc        *bool        `json:"asc,omitempty"`
	Limit      *int         `json:"limit,omitempty"`
	Offset     *int         `json:"offset,omitempty"`
}

type SetGroupPermissionInput struct {
	GroupName  string `json:"groupName"`
	Collection string `json:"collection"`
	Read       bool   `json:"read"`
	Write      bool   `json:"write"`
	Admin      bool   `json:"admin"`
}

type SetPermissionInput struct {
	Username   string `json:"username"`
	Collection string `json:"collection"`
	Read       bool   `json:"read"`
	Write      bool   `json:"write"`
	Admin      bool   `json:"admin"`
}

type SetSchemaInput struct {
	Collection string `json:"collection"`
	Schema     string `json:"schema"`
}

type Stats struct {
	DatabasePath     string             `json:"databasePath"`
	DatabaseSize     int                `json:"databaseSize"`
	Mode             string             `json:"mode"`
	Collections      []*CollectionStats `json:"collections"`
	TotalDocuments   int                `json:"totalDocuments"`
	TotalRevisions   int                `json:"totalRevisions"`
	TotalMetaIndices int                `json:"totalMetaIndices"`
}

type UpdateDocumentInput struct {
	Collection string       `json:"collection"`
	Key        string       `json:"key"`
	Lang       string       `json:"lang"`
	Meta       []*MetaInput `json:"meta,omitempty"`
	ContentMd  *string      `json:"contentMd,omitempty"`
}

type User struct {
	Username  string `json:"username"`
	Admin     bool   `json:"admin"`
	CreatedAt int64  `json:"createdAt"`
}

type UserPermission struct {
	Username   string `json:"username"`
	Collection string `json:"collection"`
	Read       bool   `json:"read"`
	Write      bool   `json:"write"`
	Admin      bool   `json:"admin"`
}

type ValidationResult struct {
	Valid  bool     `json:"valid"`
	Errors []string `json:"errors"`
	// Advisory findings that do not make the document invalid (DOC-012) — today,
	// metadata values that look like a structure lost on the way in.
	Warnings []string `json:"warnings,omitempty"`
}

type VectorCollectionStats struct {
	Collection        string `json:"collection"`
	TotalDocuments    int    `json:"totalDocuments"`
	EmbeddedDocuments int    `json:"embeddedDocuments"`
}

type VectorSearchInput struct {
	Collection     string       `json:"collection"`
	Query          *string      `json:"query,omitempty"`
	QueryVector    []float64    `json:"queryVector,omitempty"`
	TopK           *int         `json:"topK,omitempty"`
	Threshold      *float64     `json:"threshold,omitempty"`
	FilterMeta     []*MetaInput `json:"filterMeta,omitempty"`
	IncludeContent *bool        `json:"includeContent,omitempty"`
}

type VectorSearchResponse struct {
	Results    []*VectorSearchResult `json:"results"`
	Total      int                   `json:"total"`
	Model      *string               `json:"model,omitempty"`
	Dimensions *int                  `json:"dimensions,omitempty"`
}

type VectorSearchResult struct {
	Document *Document `json:"document"`
	Score    float64   `json:"score"`
	Rank     int       `json:"rank"`
}

type VectorStats struct {
	Enabled     bool                     `json:"enabled"`
	Provider    *string                  `json:"provider,omitempty"`
	Model       *string                  `json:"model,omitempty"`
	Dimensions  *int                     `json:"dimensions,omitempty"`
	Collections []*VectorCollectionStats `json:"collections"`
	IndexReady  bool                     `json:"indexReady"`
}

type Webhook struct {
	ID         string   `json:"id"`
	URL        string   `json:"url"`
	Events     []string `json:"events"`
	Collection string   `json:"collection"`
	CreatedAt  int64    `json:"createdAt"`
}

type Permission string

const (
	PermissionRead  Permission = "READ"
	PermissionWrite Permission = "WRITE"
	PermissionAdmin Permission = "ADMIN"
)

var AllPermission = []Permission{
	PermissionRead,
	PermissionWrite,
	PermissionAdmin,
}

func (e Permission) IsValid() bool {
	switch e {
	case PermissionRead, PermissionWrite, PermissionAdmin:
		return true
	}
	return false
}

func (e Permission) String() string {
	return string(e)
}

func (e *Permission) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Permission(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Permission", str)
	}
	return nil
}

func (e Permission) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Permission) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Permission) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
