package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// AddDocument is the resolver for the addDocument field.
func (r *mutationResolver) AddDocument(ctx context.Context, input AddDocumentInput) (*Document, error) {
	return r.server.AddDocument(ctx, input)
}

// UpdateDocument is the resolver for the updateDocument field.
func (r *mutationResolver) UpdateDocument(ctx context.Context, input UpdateDocumentInput) (*Document, error) {
	return r.server.UpdateDocument(ctx, input)
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, collection string, key string, lang string) (bool, error) {
	if err := r.server.DeleteDocument(ctx, collection, key, lang); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteCollection is the resolver for the deleteCollection field.
func (r *mutationResolver) DeleteCollection(ctx context.Context, collection string) (int, error) {
	return r.server.DeleteCollection(ctx, collection)
}

// AddBatch is the resolver for the addBatch field.
func (r *mutationResolver) AddBatch(ctx context.Context, collection string, documents []*AddBatchDocumentInput) (*BatchAddResult, error) {
	return r.server.AddBatch(ctx, collection, documents)
}

// IngestDocuments is the resolver for the ingestDocuments field.
func (r *mutationResolver) IngestDocuments(ctx context.Context, collection string, documents []*IngestDocumentInput, options *IngestOptionsInput) (*IngestResult, error) {
	return r.server.IngestDocuments(ctx, collection, documents, options)
}

// VectorReindex is the resolver for the vectorReindex field.
func (r *mutationResolver) VectorReindex(ctx context.Context, collection string, force *bool) (*VectorStats, error) {
	return r.server.VectorReindex(ctx, collection, force)
}

// SetTTL is the resolver for the setTTL field.
func (r *mutationResolver) SetTTL(ctx context.Context, collection string, key string, lang string, ttl int) (*Document, error) {
	return r.server.SetTTL(ctx, collection, key, lang, ttl)
}

// ImportURL is the resolver for the importURL field.
func (r *mutationResolver) ImportURL(ctx context.Context, collection string, url string, key *string, lang string, meta []*MetaInput, ttl *int) (*Document, error) {
	return r.server.ImportURL(ctx, collection, url, key, lang, meta, ttl)
}

// RegisterWebhook is the resolver for the registerWebhook field.
func (r *mutationResolver) RegisterWebhook(ctx context.Context, input RegisterWebhookInput) (*Webhook, error) {
	return r.server.RegisterWebhook(ctx, input)
}

// DeleteWebhook is the resolver for the deleteWebhook field.
func (r *mutationResolver) DeleteWebhook(ctx context.Context, id string) (bool, error) {
	if err := r.server.DeleteWebhook(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// SetSchema is the resolver for the setSchema field.
func (r *mutationResolver) SetSchema(ctx context.Context, input SetSchemaInput) (bool, error) {
	if err := r.server.SetSchema(ctx, input); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteSchema is the resolver for the deleteSchema field.
func (r *mutationResolver) DeleteSchema(ctx context.Context, collection string) (bool, error) {
	if err := r.server.DeleteSchema(ctx, collection); err != nil {
		return false, err
	}
	return true, nil
}

// ValidateDocument is the resolver for the validateDocument field.
func (r *mutationResolver) ValidateDocument(ctx context.Context, collection string, meta []*MetaInput) (*ValidationResult, error) {
	return r.server.ValidateDocument(ctx, collection, meta)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*AuthPayload, error) {
	userInfo, err := r.server.Authenticate(username, password)
	if err != nil {
		return nil, err
	}
	token, expiresAt, err := r.server.GenerateJWT(userInfo.Username, userInfo.Admin)
	if err != nil {
		return nil, err
	}
	return &AuthPayload{Token: token, ExpiresAt: expiresAt}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, password string) (*User, error) {
	return r.server.Register(ctx, username, password)
}

// CreateAPIKey is the resolver for the createAPIKey field.
func (r *mutationResolver) CreateAPIKey(ctx context.Context, input CreateAPIKeyInput) (*APIKey, error) {
	return r.server.CreateAPIKey(ctx, input)
}

// SetPermission is the resolver for the setPermission field.
func (r *mutationResolver) SetPermission(ctx context.Context, input SetPermissionInput) (bool, error) {
	if err := r.server.SetPermission(ctx, input); err != nil {
		return false, err
	}
	return true, nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input CreateGroupInput) (*Group, error) {
	return r.server.CreateGroup(ctx, input)
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, name string, description string, members []string) (*Group, error) {
	return r.server.UpdateGroup(ctx, name, description, members)
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, name string) (bool, error) {
	if err := r.server.DeleteGroup(ctx, name); err != nil {
		return false, err
	}
	return true, nil
}

// SetGroupPermission is the resolver for the setGroupPermission field.
func (r *mutationResolver) SetGroupPermission(ctx context.Context, input SetGroupPermissionInput) (bool, error) {
	if err := r.server.SetGroupPermission(ctx, input); err != nil {
		return false, err
	}
	return true, nil
}

// Document is the resolver for the document field.
func (r *queryResolver) Document(ctx context.Context, collection string, key string, lang string, env map[string]any) (*Document, error) {
	envStr := make(map[string]string, len(env))
	for k, v := range env {
		if s, ok := v.(string); ok {
			envStr[k] = s
		}
	}
	return r.server.GetDocument(ctx, collection, key, lang, envStr)
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, input SearchInput) (*DocumentConnection, error) {
	return r.server.SearchDocuments(ctx, input)
}

// VectorSearch is the resolver for the vectorSearch field.
func (r *queryResolver) VectorSearch(ctx context.Context, input VectorSearchInput) (*VectorSearchResponse, error) {
	return r.server.VectorSearch(ctx, input)
}

// VectorStats is the resolver for the vectorStats field.
func (r *queryResolver) VectorStats(ctx context.Context) (*VectorStats, error) {
	return r.server.VectorStats(ctx)
}

// Fts is the resolver for the fts field.
func (r *queryResolver) Fts(ctx context.Context, input FTSInput) (*FTSResponse, error) {
	return r.server.FullTextSearch(ctx, input)
}

// CodeGraph is the resolver for the codeGraph field.
func (r *queryResolver) CodeGraph(ctx context.Context, input CodeGraphInput) (*CodeGraph, error) {
	return r.server.CodeGraph(ctx, input)
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*Stats, error) {
	return r.server.GetStats(ctx)
}

// Webhooks is the resolver for the webhooks field.
func (r *queryResolver) Webhooks(ctx context.Context, collection *string) ([]*Webhook, error) {
	return r.server.ListWebhooks(ctx, collection)
}

// Schema is the resolver for the schema field.
func (r *queryResolver) Schema(ctx context.Context, collection string) (*Schema, error) {
	return r.server.GetSchema(ctx, collection)
}

// Schemas is the resolver for the schemas field.
func (r *queryResolver) Schemas(ctx context.Context) ([]*Schema, error) {
	return r.server.ListSchemas(ctx)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	return r.server.Me(ctx)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	return r.server.ListUsers(ctx)
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*Group, error) {
	return r.server.ListGroups(ctx)
}

// UserPermissions is the resolver for the userPermissions field.
func (r *queryResolver) UserPermissions(ctx context.Context, username string) ([]*UserPermission, error) {
	return r.server.UserPermissionsList(ctx, username)
}

// GroupPermissions is the resolver for the groupPermissions field.
func (r *queryResolver) GroupPermissions(ctx context.Context, groupName string) ([]*GroupPermission, error) {
	return r.server.GroupPermissionsList(ctx, groupName)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
