// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.0
// source: proto/mddb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Document represents a markdown document
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Meta          map[string]*MetaValues `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentMd     string                 `protobuf:"bytes,5,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	AddedAt       int64                  `protobuf:"varint,6,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_mddb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Document) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Document) GetMeta() map[string]*MetaValues {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Document) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *Document) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

func (x *Document) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// MetaValues holds multiple values for a metadata key
type MetaValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaValues) Reset() {
	*x = MetaValues{}
	mi := &file_proto_mddb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaValues) ProtoMessage() {}

func (x *MetaValues) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaValues.ProtoReflect.Descriptor instead.
func (*MetaValues) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{1}
}

func (x *MetaValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Add/Update document request
type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Meta          map[string]*MetaValues `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentMd     string                 `protobuf:"bytes,5,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	SaveRevision  bool                   `protobuf:"varint,6,opt,name=save_revision,json=saveRevision,proto3" json:"save_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_proto_mddb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{2}
}

func (x *AddRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AddRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *AddRequest) GetMeta() map[string]*MetaValues {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AddRequest) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *AddRequest) GetSaveRevision() bool {
	if x != nil {
		return x.SaveRevision
	}
	return false
}

// Batch add request
type AddBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Documents     []*BatchDocument       `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBatchRequest) Reset() {
	*x = AddBatchRequest{}
	mi := &file_proto_mddb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBatchRequest) ProtoMessage() {}

func (x *AddBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBatchRequest.ProtoReflect.Descriptor instead.
func (*AddBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{3}
}

func (x *AddBatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AddBatchRequest) GetDocuments() []*BatchDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

// Document for batch operations
type BatchDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Meta          map[string]*MetaValues `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentMd     string                 `protobuf:"bytes,4,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	SaveRevision  bool                   `protobuf:"varint,5,opt,name=save_revision,json=saveRevision,proto3" json:"save_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDocument) Reset() {
	*x = BatchDocument{}
	mi := &file_proto_mddb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDocument) ProtoMessage() {}

func (x *BatchDocument) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDocument.ProtoReflect.Descriptor instead.
func (*BatchDocument) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{4}
}

func (x *BatchDocument) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BatchDocument) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *BatchDocument) GetMeta() map[string]*MetaValues {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *BatchDocument) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *BatchDocument) GetSaveRevision() bool {
	if x != nil {
		return x.SaveRevision
	}
	return false
}

// Batch add response
type AddBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         int32                  `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Updated       int32                  `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"` // Error messages for failed documents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBatchResponse) Reset() {
	*x = AddBatchResponse{}
	mi := &file_proto_mddb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBatchResponse) ProtoMessage() {}

func (x *AddBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBatchResponse.ProtoReflect.Descriptor instead.
func (*AddBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{5}
}

func (x *AddBatchResponse) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *AddBatchResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *AddBatchResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *AddBatchResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Get document request
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Template variables
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_mddb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *GetRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// Search request
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	FilterMeta    map[string]*MetaValues `protobuf:"bytes,2,rep,name=filter_meta,json=filterMeta,proto3" json:"filter_meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"` // addedAt, updatedAt, key
	Asc           bool                   `protobuf:"varint,4,opt,name=asc,proto3" json:"asc,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_mddb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{7}
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchRequest) GetFilterMeta() map[string]*MetaValues {
	if x != nil {
		return x.FilterMeta
	}
	return nil
}

func (x *SearchRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchRequest) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Search response
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_mddb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Export request
type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	FilterMeta    map[string]*MetaValues `protobuf:"bytes,2,rep,name=filter_meta,json=filterMeta,proto3" json:"filter_meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // ndjson, zip
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_proto_mddb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{9}
}

func (x *ExportRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ExportRequest) GetFilterMeta() map[string]*MetaValues {
	if x != nil {
		return x.FilterMeta
	}
	return nil
}

func (x *ExportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// Export chunk (streaming)
type ExportChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,2,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportChunk) Reset() {
	*x = ExportChunk{}
	mi := &file_proto_mddb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportChunk) ProtoMessage() {}

func (x *ExportChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportChunk.ProtoReflect.Descriptor instead.
func (*ExportChunk) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{10}
}

func (x *ExportChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExportChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// Backup request
type BackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"` // Backup filename
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_proto_mddb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{11}
}

func (x *BackupRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// Backup response
type BackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backup        string                 `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	mi := &file_proto_mddb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{12}
}

func (x *BackupResponse) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

// Restore request
type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // Backup filename
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_proto_mddb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{13}
}

func (x *RestoreRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

// Restore response
type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restored      string                 `protobuf:"bytes,1,opt,name=restored,proto3" json:"restored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_proto_mddb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{14}
}

func (x *RestoreResponse) GetRestored() string {
	if x != nil {
		return x.Restored
	}
	return ""
}

// Truncate request
type TruncateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	KeepRevs      int32                  `protobuf:"varint,2,opt,name=keep_revs,json=keepRevs,proto3" json:"keep_revs,omitempty"`
	DropCache     bool                   `protobuf:"varint,3,opt,name=drop_cache,json=dropCache,proto3" json:"drop_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateRequest) Reset() {
	*x = TruncateRequest{}
	mi := &file_proto_mddb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateRequest) ProtoMessage() {}

func (x *TruncateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateRequest.ProtoReflect.Descriptor instead.
func (*TruncateRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{15}
}

func (x *TruncateRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *TruncateRequest) GetKeepRevs() int32 {
	if x != nil {
		return x.KeepRevs
	}
	return 0
}

func (x *TruncateRequest) GetDropCache() bool {
	if x != nil {
		return x.DropCache
	}
	return false
}

// Truncate response
type TruncateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateResponse) Reset() {
	*x = TruncateResponse{}
	mi := &file_proto_mddb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateResponse) ProtoMessage() {}

func (x *TruncateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateResponse.ProtoReflect.Descriptor instead.
func (*TruncateResponse) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{16}
}

func (x *TruncateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Stats request
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_mddb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{17}
}

// Stats response
type StatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DatabasePath     string                 `protobuf:"bytes,1,opt,name=database_path,json=databasePath,proto3" json:"database_path,omitempty"`
	DatabaseSize     int64                  `protobuf:"varint,2,opt,name=database_size,json=databaseSize,proto3" json:"database_size,omitempty"`
	Mode             string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Collections      []*CollectionStats     `protobuf:"bytes,4,rep,name=collections,proto3" json:"collections,omitempty"`
	TotalDocuments   int32                  `protobuf:"varint,5,opt,name=total_documents,json=totalDocuments,proto3" json:"total_documents,omitempty"`
	TotalRevisions   int32                  `protobuf:"varint,6,opt,name=total_revisions,json=totalRevisions,proto3" json:"total_revisions,omitempty"`
	TotalMetaIndices int32                  `protobuf:"varint,7,opt,name=total_meta_indices,json=totalMetaIndices,proto3" json:"total_meta_indices,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_mddb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{18}
}

func (x *StatsResponse) GetDatabasePath() string {
	if x != nil {
		return x.DatabasePath
	}
	return ""
}

func (x *StatsResponse) GetDatabaseSize() int64 {
	if x != nil {
		return x.DatabaseSize
	}
	return 0
}

func (x *StatsResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StatsResponse) GetCollections() []*CollectionStats {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *StatsResponse) GetTotalDocuments() int32 {
	if x != nil {
		return x.TotalDocuments
	}
	return 0
}

func (x *StatsResponse) GetTotalRevisions() int32 {
	if x != nil {
		return x.TotalRevisions
	}
	return 0
}

func (x *StatsResponse) GetTotalMetaIndices() int32 {
	if x != nil {
		return x.TotalMetaIndices
	}
	return 0
}

// Collection statistics
type CollectionStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DocumentCount  int32                  `protobuf:"varint,2,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	RevisionCount  int32                  `protobuf:"varint,3,opt,name=revision_count,json=revisionCount,proto3" json:"revision_count,omitempty"`
	MetaIndexCount int32                  `protobuf:"varint,4,opt,name=meta_index_count,json=metaIndexCount,proto3" json:"meta_index_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectionStats) Reset() {
	*x = CollectionStats{}
	mi := &file_proto_mddb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionStats) ProtoMessage() {}

func (x *CollectionStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionStats.ProtoReflect.Descriptor instead.
func (*CollectionStats) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{19}
}

func (x *CollectionStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionStats) GetDocumentCount() int32 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *CollectionStats) GetRevisionCount() int32 {
	if x != nil {
		return x.RevisionCount
	}
	return 0
}

func (x *CollectionStats) GetMetaIndexCount() int32 {
	if x != nil {
		return x.MetaIndexCount
	}
	return 0
}

// Update batch request
type UpdateBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Documents     []*UpdateDocument      `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBatchRequest) Reset() {
	*x = UpdateBatchRequest{}
	mi := &file_proto_mddb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatchRequest) ProtoMessage() {}

func (x *UpdateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatchRequest.ProtoReflect.Descriptor instead.
func (*UpdateBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateBatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpdateBatchRequest) GetDocuments() []*UpdateDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

// Document for update operations
type UpdateDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Meta          map[string]*MetaValues `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentMd     string                 `protobuf:"bytes,4,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	SaveRevision  bool                   `protobuf:"varint,5,opt,name=save_revision,json=saveRevision,proto3" json:"save_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocument) Reset() {
	*x = UpdateDocument{}
	mi := &file_proto_mddb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocument) ProtoMessage() {}

func (x *UpdateDocument) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocument.ProtoReflect.Descriptor instead.
func (*UpdateDocument) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateDocument) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateDocument) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *UpdateDocument) GetMeta() map[string]*MetaValues {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *UpdateDocument) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *UpdateDocument) GetSaveRevision() bool {
	if x != nil {
		return x.SaveRevision
	}
	return false
}

// Update batch response
type UpdateBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       int32                  `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	NotFound      int32                  `protobuf:"varint,4,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBatchResponse) Reset() {
	*x = UpdateBatchResponse{}
	mi := &file_proto_mddb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatchResponse) ProtoMessage() {}

func (x *UpdateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatchResponse.ProtoReflect.Descriptor instead.
func (*UpdateBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateBatchResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *UpdateBatchResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *UpdateBatchResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *UpdateBatchResponse) GetNotFound() int32 {
	if x != nil {
		return x.NotFound
	}
	return 0
}

// Delete batch request
type DeleteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Documents     []*DeleteDocument      `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBatchRequest) Reset() {
	*x = DeleteBatchRequest{}
	mi := &file_proto_mddb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBatchRequest) ProtoMessage() {}

func (x *DeleteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteBatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteBatchRequest) GetDocuments() []*DeleteDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

// Document for delete operations
type DeleteDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocument) Reset() {
	*x = DeleteDocument{}
	mi := &file_proto_mddb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocument) ProtoMessage() {}

func (x *DeleteDocument) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocument.ProtoReflect.Descriptor instead.
func (*DeleteDocument) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteDocument) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteDocument) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// Delete batch response
type DeleteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int32                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	NotFound      int32                  `protobuf:"varint,4,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBatchResponse) Reset() {
	*x = DeleteBatchResponse{}
	mi := &file_proto_mddb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBatchResponse) ProtoMessage() {}

func (x *DeleteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mddb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBatchResponse.ProtoReflect.Descriptor instead.
func (*DeleteBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_mddb_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteBatchResponse) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteBatchResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *DeleteBatchResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *DeleteBatchResponse) GetNotFound() int32 {
	if x != nil {
		return x.NotFound
	}
	return 0
}

var File_proto_mddb_proto protoreflect.FileDescriptor

const file_proto_mddb_proto_rawDesc = "" +
	"\n" +
	"\x10proto/mddb.proto\x12\x04mddb\"\x92\x02\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12,\n" +
	"\x04meta\x18\x04 \x03(\v2\x18.mddb.Document.MetaEntryR\x04meta\x12\x1d\n" +
	"\n" +
	"content_md\x18\x05 \x01(\tR\tcontentMd\x12\x19\n" +
	"\badded_at\x18\x06 \x01(\x03R\aaddedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x1aI\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.mddb.MetaValuesR\x05value:\x028\x01\"$\n" +
	"\n" +
	"MetaValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x91\x02\n" +
	"\n" +
	"AddRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12.\n" +
	"\x04meta\x18\x04 \x03(\v2\x1a.mddb.AddRequest.MetaEntryR\x04meta\x12\x1d\n" +
	"\n" +
	"content_md\x18\x05 \x01(\tR\tcontentMd\x12#\n" +
	"\rsave_revision\x18\x06 \x01(\bR\fsaveRevision\x1aI\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.mddb.MetaValuesR\x05value:\x028\x01\"d\n" +
	"\x0fAddBatchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x121\n" +
	"\tdocuments\x18\x02 \x03(\v2\x13.mddb.BatchDocumentR\tdocuments\"\xf7\x01\n" +
	"\rBatchDocument\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x121\n" +
	"\x04meta\x18\x03 \x03(\v2\x1d.mddb.BatchDocument.MetaEntryR\x04meta\x12\x1d\n" +
	"\n" +
	"content_md\x18\x04 \x01(\tR\tcontentMd\x12#\n" +
	"\rsave_revision\x18\x05 \x01(\bR\fsaveRevision\x1aI\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.mddb.MetaValuesR\x05value:\x028\x01\"r\n" +
	"\x10AddBatchResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x05R\x05added\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\x05R\aupdated\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"\xb7\x01\n" +
	"\n" +
	"GetRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12+\n" +
	"\x03env\x18\x04 \x03(\v2\x19.mddb.GetRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x02\n" +
	"\rSearchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12D\n" +
	"\vfilter_meta\x18\x02 \x03(\v2#.mddb.SearchRequest.FilterMetaEntryR\n" +
	"filterMeta\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x10\n" +
	"\x03asc\x18\x04 \x01(\bR\x03asc\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\x1aO\n" +
	"\x0fFilterMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.mddb.MetaValuesR\x05value:\x028\x01\"T\n" +
	"\x0eSearchResponse\x12,\n" +
	"\tdocuments\x18\x01 \x03(\v2\x0e.mddb.DocumentR\tdocuments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xde\x01\n" +
	"\rExportRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12D\n" +
	"\vfilter_meta\x18\x02 \x03(\v2#.mddb.ExportRequest.FilterMetaEntryR\n" +
	"filterMeta\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x1aO\n" +
	"\x0fFilterMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.mddb.MetaValuesR\x05value:\x028\x01\":\n" +
	"\vExportChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x02 \x01(\bR\x06isLast\"\x1f\n" +
	"\rBackupRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\"(\n" +
	"\x0eBackupResponse\x12\x16\n" +
	"\x06backup\x18\x01 \x01(\tR\x06backup\"$\n" +
	"\x0eRestoreRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\"-\n" +
	"\x0fRestoreResponse\x12\x1a\n" +
	"\brestored\x18\x01 \x01(\tR\brestored\"m\n" +
	"\x0fTruncateRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1b\n" +
	"\tkeep_revs\x18\x02 \x01(\x05R\bkeepRevs\x12\x1d\n" +
	"\n" +
	"drop_cache\x18\x03 \x01(\bR\tdropCache\"*\n" +
	"\x10TruncateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x0e\n" +
	"\fStatsRequest\"\xa6\x02\n" +
	"\rStatsResponse\x12#\n" +
	"\rdatabase_path\x18\x01 \x01(\tR\fdatabasePath\x12#\n" +
	"\rdatabase_size\x18\x02 \x01(\x03R\fdatabaseSize\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x127\n" +
	"\vcollections\x18\x04 \x03(\v2\x15.mddb.CollectionStatsR\vcollections\x12'\n" +
	"\x0ftotal_documents\x18\x05 \x01(\x05R\x0etotalDocuments\x12'\n" +
	"\x0ftotal_revisions\x18\x06 \x01(\x05R\x0etotalRevisions\x12,\n" +
	"\x12total_meta_indices\x18\a \x01(\x05R\x10totalMetaIndices\"\x9d\x01\n" +
	"\x0fCollectionStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0edocument_count\x18\x02 \x01(\x05R\rdocumentCount\x12%\n" +
	"\x0erevision_count\x18\x03 \x01(\x05R\rrevisionCount\x12(\n" +
	"\x10meta_index_count\x18\x04 \x01(\x05R\x0emetaIndexCount\"h\n" +
	"\x12UpdateBatchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x122\n" +
	"\tdocuments\x18\x02 \x03(\v2\x14.mddb.UpdateDocumentR\tdocuments\"\xf9\x01\n" +
	"\x0eUpdateDocument\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x122\n" +
	"\x04meta\x18\x03 \x03(\v2\x1e.mddb.UpdateDocument.MetaEntryR\x04meta\x12\x1d\n" +
	"\n" +
	"content_md\x18\x04 \x01(\tR\tcontentMd\x12#\n" +
	"\rsave_revision\x18\x05 \x01(\bR\fsaveRevision\x1aI\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.mddb.MetaValuesR\x05value:\x028\x01\"|\n" +
	"\x13UpdateBatchResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\x05R\aupdated\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12\x1b\n" +
	"\tnot_found\x18\x04 \x01(\x05R\bnotFound\"h\n" +
	"\x12DeleteBatchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x122\n" +
	"\tdocuments\x18\x02 \x03(\v2\x14.mddb.DeleteDocumentR\tdocuments\"6\n" +
	"\x0eDeleteDocument\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"|\n" +
	"\x13DeleteBatchResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x05R\adeleted\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12\x1b\n" +
	"\tnot_found\x18\x04 \x01(\x05R\bnotFound2\xde\x04\n" +
	"\x04MDDB\x12'\n" +
	"\x03Add\x12\x10.mddb.AddRequest\x1a\x0e.mddb.Document\x129\n" +
	"\bAddBatch\x12\x15.mddb.AddBatchRequest\x1a\x16.mddb.AddBatchResponse\x12B\n" +
	"\vUpdateBatch\x12\x18.mddb.UpdateBatchRequest\x1a\x19.mddb.UpdateBatchResponse\x12B\n" +
	"\vDeleteBatch\x12\x18.mddb.DeleteBatchRequest\x1a\x19.mddb.DeleteBatchResponse\x12'\n" +
	"\x03Get\x12\x10.mddb.GetRequest\x1a\x0e.mddb.Document\x123\n" +
	"\x06Search\x12\x13.mddb.SearchRequest\x1a\x14.mddb.SearchResponse\x122\n" +
	"\x06Export\x12\x13.mddb.ExportRequest\x1a\x11.mddb.ExportChunk0\x01\x123\n" +
	"\x06Backup\x12\x13.mddb.BackupRequest\x1a\x14.mddb.BackupResponse\x126\n" +
	"\aRestore\x12\x14.mddb.RestoreRequest\x1a\x15.mddb.RestoreResponse\x129\n" +
	"\bTruncate\x12\x15.mddb.TruncateRequest\x1a\x16.mddb.TruncateResponse\x120\n" +
	"\x05Stats\x12\x12.mddb.StatsRequest\x1a\x13.mddb.StatsResponseB\fZ\n" +
	"mddb/protob\x06proto3"

var (
	file_proto_mddb_proto_rawDescOnce sync.Once
	file_proto_mddb_proto_rawDescData []byte
)

func file_proto_mddb_proto_rawDescGZIP() []byte {
	file_proto_mddb_proto_rawDescOnce.Do(func() {
		file_proto_mddb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mddb_proto_rawDesc), len(file_proto_mddb_proto_rawDesc)))
	})
	return file_proto_mddb_proto_rawDescData
}

var file_proto_mddb_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_mddb_proto_goTypes = []any{
	(*Document)(nil),            // 0: mddb.Document
	(*MetaValues)(nil),          // 1: mddb.MetaValues
	(*AddRequest)(nil),          // 2: mddb.AddRequest
	(*AddBatchRequest)(nil),     // 3: mddb.AddBatchRequest
	(*BatchDocument)(nil),       // 4: mddb.BatchDocument
	(*AddBatchResponse)(nil),    // 5: mddb.AddBatchResponse
	(*GetRequest)(nil),          // 6: mddb.GetRequest
	(*SearchRequest)(nil),       // 7: mddb.SearchRequest
	(*SearchResponse)(nil),      // 8: mddb.SearchResponse
	(*ExportRequest)(nil),       // 9: mddb.ExportRequest
	(*ExportChunk)(nil),         // 10: mddb.ExportChunk
	(*BackupRequest)(nil),       // 11: mddb.BackupRequest
	(*BackupResponse)(nil),      // 12: mddb.BackupResponse
	(*RestoreRequest)(nil),      // 13: mddb.RestoreRequest
	(*RestoreResponse)(nil),     // 14: mddb.RestoreResponse
	(*TruncateRequest)(nil),     // 15: mddb.TruncateRequest
	(*TruncateResponse)(nil),    // 16: mddb.TruncateResponse
	(*StatsRequest)(nil),        // 17: mddb.StatsRequest
	(*StatsResponse)(nil),       // 18: mddb.StatsResponse
	(*CollectionStats)(nil),     // 19: mddb.CollectionStats
	(*UpdateBatchRequest)(nil),  // 20: mddb.UpdateBatchRequest
	(*UpdateDocument)(nil),      // 21: mddb.UpdateDocument
	(*UpdateBatchResponse)(nil), // 22: mddb.UpdateBatchResponse
	(*DeleteBatchRequest)(nil),  // 23: mddb.DeleteBatchRequest
	(*DeleteDocument)(nil),      // 24: mddb.DeleteDocument
	(*DeleteBatchResponse)(nil), // 25: mddb.DeleteBatchResponse
	nil,                         // 26: mddb.Document.MetaEntry
	nil,                         // 27: mddb.AddRequest.MetaEntry
	nil,                         // 28: mddb.BatchDocument.MetaEntry
	nil,                         // 29: mddb.GetRequest.EnvEntry
	nil,                         // 30: mddb.SearchRequest.FilterMetaEntry
	nil,                         // 31: mddb.ExportRequest.FilterMetaEntry
	nil,                         // 32: mddb.UpdateDocument.MetaEntry
}
var file_proto_mddb_proto_depIdxs = []int32{
	26, // 0: mddb.Document.meta:type_name -> mddb.Document.MetaEntry
	27, // 1: mddb.AddRequest.meta:type_name -> mddb.AddRequest.MetaEntry
	4,  // 2: mddb.AddBatchRequest.documents:type_name -> mddb.BatchDocument
	28, // 3: mddb.BatchDocument.meta:type_name -> mddb.BatchDocument.MetaEntry
	29, // 4: mddb.GetRequest.env:type_name -> mddb.GetRequest.EnvEntry
	30, // 5: mddb.SearchRequest.filter_meta:type_name -> mddb.SearchRequest.FilterMetaEntry
	0,  // 6: mddb.SearchResponse.documents:type_name -> mddb.Document
	31, // 7: mddb.ExportRequest.filter_meta:type_name -> mddb.ExportRequest.FilterMetaEntry
	19, // 8: mddb.StatsResponse.collections:type_name -> mddb.CollectionStats
	21, // 9: mddb.UpdateBatchRequest.documents:type_name -> mddb.UpdateDocument
	32, // 10: mddb.UpdateDocument.meta:type_name -> mddb.UpdateDocument.MetaEntry
	24, // 11: mddb.DeleteBatchRequest.documents:type_name -> mddb.DeleteDocument
	1,  // 12: mddb.Document.MetaEntry.value:type_name -> mddb.MetaValues
	1,  // 13: mddb.AddRequest.MetaEntry.value:type_name -> mddb.MetaValues
	1,  // 14: mddb.BatchDocument.MetaEntry.value:type_name -> mddb.MetaValues
	1,  // 15: mddb.SearchRequest.FilterMetaEntry.value:type_name -> mddb.MetaValues
	1,  // 16: mddb.ExportRequest.FilterMetaEntry.value:type_name -> mddb.MetaValues
	1,  // 17: mddb.UpdateDocument.MetaEntry.value:type_name -> mddb.MetaValues
	2,  // 18: mddb.MDDB.Add:input_type -> mddb.AddRequest
	3,  // 19: mddb.MDDB.AddBatch:input_type -> mddb.AddBatchRequest
	20, // 20: mddb.MDDB.UpdateBatch:input_type -> mddb.UpdateBatchRequest
	23, // 21: mddb.MDDB.DeleteBatch:input_type -> mddb.DeleteBatchRequest
	6,  // 22: mddb.MDDB.Get:input_type -> mddb.GetRequest
	7,  // 23: mddb.MDDB.Search:input_type -> mddb.SearchRequest
	9,  // 24: mddb.MDDB.Export:input_type -> mddb.ExportRequest
	11, // 25: mddb.MDDB.Backup:input_type -> mddb.BackupRequest
	13, // 26: mddb.MDDB.Restore:input_type -> mddb.RestoreRequest
	15, // 27: mddb.MDDB.Truncate:input_type -> mddb.TruncateRequest
	17, // 28: mddb.MDDB.Stats:input_type -> mddb.StatsRequest
	0,  // 29: mddb.MDDB.Add:output_type -> mddb.Document
	5,  // 30: mddb.MDDB.AddBatch:output_type -> mddb.AddBatchResponse
	22, // 31: mddb.MDDB.UpdateBatch:output_type -> mddb.UpdateBatchResponse
	25, // 32: mddb.MDDB.DeleteBatch:output_type -> mddb.DeleteBatchResponse
	0,  // 33: mddb.MDDB.Get:output_type -> mddb.Document
	8,  // 34: mddb.MDDB.Search:output_type -> mddb.SearchResponse
	10, // 35: mddb.MDDB.Export:output_type -> mddb.ExportChunk
	12, // 36: mddb.MDDB.Backup:output_type -> mddb.BackupResponse
	14, // 37: mddb.MDDB.Restore:output_type -> mddb.RestoreResponse
	16, // 38: mddb.MDDB.Truncate:output_type -> mddb.TruncateResponse
	18, // 39: mddb.MDDB.Stats:output_type -> mddb.StatsResponse
	29, // [29:40] is the sub-list for method output_type
	18, // [18:29] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_mddb_proto_init() }
func file_proto_mddb_proto_init() {
	if File_proto_mddb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mddb_proto_rawDesc), len(file_proto_mddb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mddb_proto_goTypes,
		DependencyIndexes: file_proto_mddb_proto_depIdxs,
		MessageInfos:      file_proto_mddb_proto_msgTypes,
	}.Build()
	File_proto_mddb_proto = out.File
	file_proto_mddb_proto_goTypes = nil
	file_proto_mddb_proto_depIdxs = nil
}
